---


version: '2.3'


################################################################################
# SERVICES
################################################################################
services:


  # ------------------------------------------------------------
  # PHP
  # ------------------------------------------------------------
  php:
    image: devilbox/php-fpm:8.0-work-0.130
    env_file:
        - ./.env-docker-compose
    volumes:
        - .:/shared/httpd
    ports:
      - "127.0.0.1:8000:8000"
    network_mode: 'host'

#    command: bash -l # per aprire una shell direttamente dentro alla macchina
#    command: ./vendor/bin/phpunit # per lanciare direttamente la php unit
    command:  php artisan serve  # per testare le api con composer postman







